CREATE TABLE
    USER_ACCOUNT(
        SSN int(10) PRIMARY KEY,
        NAME VARCHAR(50) not null,
        PHONE_NUMBER VARCHAR(20),
        BALANCE FLOAT DEFAULT(0),
        BANK_ID int ,
        BANK_NUMBER int ,
        PBA_VERIFIED BOOLEAN NOT NULL DEFAULT(FALSE),
        CONSTRAINT FK_PHONE FOREIGN KEY(PHONE_NUMBER) REFERENCES ELEC_ADDRESS(IDENTIFIER)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
        CONSTRAINT FK_BANK_ID1 FOREIGN kEY(BANK_ID,BANK_NUMBER) REFERENCES BANK_ACCOUNT(BANK_ID,BANK_NUMBER)
        ON UPDATE CASCADE
        ON DELETE CASCADE
    )