CREATE TABLE
    HAS_ADDITIONAL(
        SSN int NOT NULL,
        BANK_ID int NOT NULL,
        BANK_NUMBER int NOT NULL,
        VERIFIED BOOLEAN DEFAULT(FALSE),
        CONSTRAINT FK_SSN FOREIGN kEY(SSN) REFERENCES USER_ACCOUNT(SSN) ON UPDATE CASCADE
        ON DELETE CASCADE,
        CONSTRAINT FK_BANK_ID FOREIGN kEY(BANK_ID,BANK_NUMBER) REFERENCES BANK_ACCOUNT(BANK_ID,BANK_NUMBER) ON UPDATE CASCADE
        ON DELETE CASCADE
    )