CREATE TABLE
    SEND_TRANSACTION(
        STID int auto_increment PRIMARY KEY,
        AMOUNT INT NOT NULL,
        MEMO VARCHAR(40),
        CANCEL_REASON VARCHAR(40),
        IDENTIFIER VARCHAR(20),
        SSN INT ,
        DATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT FK_IDENTIFIER FOREIGN KEY(IDENTIFIER) REFERENCES ELEC_ADDRESS(IDENTIFIER) ON UPDATE CASCADE
        ON DELETE CASCADE,
        CONSTRAINT FK_SSN_SEND FOREIGN KEY(SSN) REFERENCES USER_ACCOUNT(SSN) ON UPDATE CASCADE
        ON DELETE CASCADE
        
    )