CREATE TABLE
    REQUEST_TRANSACTION(
        RT_ID int auto_increment PRIMARY KEY,
        AMOUNT INT NOT NULL,
        MEMO VARCHAR(40),
        SSN INT ,
        DATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        #CONSTRAINT FK_RTID FOREIGN KEY(RT_ID) REFERENCES FROM_TRANSACTION(RT_ID),
        CONSTRAINT FK_SSN_REQUEST FOREIGN KEY(SSN) REFERENCES USER_ACCOUNT(SSN) ON UPDATE CASCADE
        ON DELETE CASCADE
        
    )