CREATE TABLE
    PHONE(
        PHONE_NO VARCHAR(20) PRIMARY KEY,
        SSN int NOT NULL,
        CONSTRAINT FK_SSN2 FOREIGN kEY(SSN) REFERENCES USER_ACCOUNT(SSN) ON UPDATE CASCADE
        ON DELETE CASCADE,
        CONSTRAINT FK_PHONE_1 FOREIGN kEY(PHONE_NO) REFERENCES ELEC_ADDRESS(IDENTIFIER) ON UPDATE CASCADE
        ON DELETE CASCADE
    )